# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orchestration.v1 import orchestration_pb2 as orchestration_dot_v1_dot_orchestration__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestration/v1/orchestration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeStub(object):
    """--- 服务定义 ---

    Agent Runtime 暴露给编排引擎的 gRPC 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteNode = channel.unary_unary(
                '/orchestration.v1.AgentRuntime/ExecuteNode',
                request_serializer=orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeRequest.SerializeToString,
                response_deserializer=orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeResponse.FromString,
                _registered_method=True)


class AgentRuntimeServicer(object):
    """--- 服务定义 ---

    Agent Runtime 暴露给编排引擎的 gRPC 服务
    """

    def ExecuteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteNode,
                    request_deserializer=orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeRequest.FromString,
                    response_serializer=orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestration.v1.AgentRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestration.v1.AgentRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntime(object):
    """--- 服务定义 ---

    Agent Runtime 暴露给编排引擎的 gRPC 服务
    """

    @staticmethod
    def ExecuteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestration.v1.AgentRuntime/ExecuteNode',
            orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeRequest.SerializeToString,
            orchestration_dot_v1_dot_orchestration__pb2.ExecuteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
