# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestration/v1/orchestration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestration/v1/orchestration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$orchestration/v1/orchestration.proto\x12\x10orchestration.v1\"\xd1\x01\n\x12\x45xecuteNodeRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x12\n\nagent_type\x18\x03 \x01(\t\x12\x15\n\rsystem_prompt\x18\x04 \x01(\t\x12\x12\n\nuser_input\x18\x05 \x01(\t\x12%\n\x05tools\x18\x06 \x03(\x0b\x32\x16.orchestration.v1.Tool\x12/\n\x06memory\x18\x07 \x01(\x0b\x32\x1f.orchestration.v1.MemoryContext\"^\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0bschema_json\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x05 \x01(\t\"q\n\rMemoryContext\x12-\n\nshort_term\x18\x01 \x03(\x0b\x32\x19.orchestration.v1.Message\x12\x31\n\x0elong_term_hits\x18\x02 \x03(\x0b\x32\x19.orchestration.v1.Message\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x9a\x01\n\x13\x45xecuteNodeResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12.\n\ntool_calls\x18\x04 \x03(\x0b\x32\x1a.orchestration.v1.ToolCall\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"F\n\x08ToolCall\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x12\n\ninput_json\x18\x02 \x01(\t\x12\x13\n\x0boutput_json\x18\x03 \x01(\t2j\n\x0c\x41gentRuntime\x12Z\n\x0b\x45xecuteNode\x12$.orchestration.v1.ExecuteNodeRequest\x1a%.orchestration.v1.ExecuteNodeResponseBNZLgithub.com/Rainnylxy/AgentFlow/engine/proto/orchestration/v1;orchestrationv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestration.v1.orchestration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/Rainnylxy/AgentFlow/engine/proto/orchestration/v1;orchestrationv1'
  _globals['_EXECUTENODEREQUEST']._serialized_start=59
  _globals['_EXECUTENODEREQUEST']._serialized_end=268
  _globals['_TOOL']._serialized_start=270
  _globals['_TOOL']._serialized_end=364
  _globals['_MEMORYCONTEXT']._serialized_start=366
  _globals['_MEMORYCONTEXT']._serialized_end=479
  _globals['_MESSAGE']._serialized_start=481
  _globals['_MESSAGE']._serialized_end=521
  _globals['_EXECUTENODERESPONSE']._serialized_start=524
  _globals['_EXECUTENODERESPONSE']._serialized_end=678
  _globals['_TOOLCALL']._serialized_start=680
  _globals['_TOOLCALL']._serialized_end=750
  _globals['_AGENTRUNTIME']._serialized_start=752
  _globals['_AGENTRUNTIME']._serialized_end=858
# @@protoc_insertion_point(module_scope)
