// AgentFlow 编排引擎通信契约
// 定义 Go Orchestration Engine 与 Python Agent Runtime 之间的 gRPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: orchestration/v1/orchestration.proto

package orchestrationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 编排引擎向 Agent Runtime 发起的执行请求
type ExecuteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "react" | "plan_execute"
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	UserInput     string                 `protobuf:"bytes,5,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	Memory        *MemoryContext         `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNodeRequest) Reset() {
	*x = ExecuteNodeRequest{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNodeRequest) ProtoMessage() {}

func (x *ExecuteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteNodeRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteNodeRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *ExecuteNodeRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ExecuteNodeRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *ExecuteNodeRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ExecuteNodeRequest) GetMemory() *MemoryContext {
	if x != nil {
		return x.Memory
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"` // JSON Schema of tool parameters
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                               // "mcp" | "rest" | "local"
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type MemoryContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortTerm     []*Message             `protobuf:"bytes,1,rep,name=short_term,json=shortTerm,proto3" json:"short_term,omitempty"`
	LongTermHits  []*Message             `protobuf:"bytes,2,rep,name=long_term_hits,json=longTermHits,proto3" json:"long_term_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryContext) Reset() {
	*x = MemoryContext{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryContext) ProtoMessage() {}

func (x *MemoryContext) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryContext.ProtoReflect.Descriptor instead.
func (*MemoryContext) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryContext) GetShortTerm() []*Message {
	if x != nil {
		return x.ShortTerm
	}
	return nil
}

func (x *MemoryContext) GetLongTermHits() []*Message {
	if x != nil {
		return x.LongTermHits
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExecuteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" | "failed" | "timeout"
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNodeResponse) Reset() {
	*x = ExecuteNodeResponse{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNodeResponse) ProtoMessage() {}

func (x *ExecuteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteNodeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteNodeResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ExecuteNodeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OutputJson    string                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_v1_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_orchestration_v1_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ToolCall) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

var File_orchestration_v1_orchestration_proto protoreflect.FileDescriptor

const file_orchestration_v1_orchestration_proto_rawDesc = "" +
	"\n" +
	"$orchestration/v1/orchestration.proto\x12\x10orchestration.v1\"\x98\x02\n" +
	"\x12ExecuteNodeRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"user_input\x18\x05 \x01(\tR\tuserInput\x12,\n" +
	"\x05tools\x18\x06 \x03(\v2\x16.orchestration.v1.ToolR\x05tools\x127\n" +
	"\x06memory\x18\a \x01(\v2\x1f.orchestration.v1.MemoryContextR\x06memory\"\x8d\x01\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\x8a\x01\n" +
	"\rMemoryContext\x128\n" +
	"\n" +
	"short_term\x18\x01 \x03(\v2\x19.orchestration.v1.MessageR\tshortTerm\x12?\n" +
	"\x0elong_term_hits\x18\x02 \x03(\v2\x19.orchestration.v1.MessageR\flongTermHits\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xd0\x01\n" +
	"\x13ExecuteNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x129\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x1a.orchestration.v1.ToolCallR\ttoolCalls\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"g\n" +
	"\bToolCall\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson2j\n" +
	"\fAgentRuntime\x12Z\n" +
	"\vExecuteNode\x12$.orchestration.v1.ExecuteNodeRequest\x1a%.orchestration.v1.ExecuteNodeResponseBNZLgithub.com/Rainnylxy/AgentFlow/engine/proto/orchestration/v1;orchestrationv1b\x06proto3"

var (
	file_orchestration_v1_orchestration_proto_rawDescOnce sync.Once
	file_orchestration_v1_orchestration_proto_rawDescData []byte
)

func file_orchestration_v1_orchestration_proto_rawDescGZIP() []byte {
	file_orchestration_v1_orchestration_proto_rawDescOnce.Do(func() {
		file_orchestration_v1_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestration_v1_orchestration_proto_rawDesc), len(file_orchestration_v1_orchestration_proto_rawDesc)))
	})
	return file_orchestration_v1_orchestration_proto_rawDescData
}

var file_orchestration_v1_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_orchestration_v1_orchestration_proto_goTypes = []any{
	(*ExecuteNodeRequest)(nil),  // 0: orchestration.v1.ExecuteNodeRequest
	(*Tool)(nil),                // 1: orchestration.v1.Tool
	(*MemoryContext)(nil),       // 2: orchestration.v1.MemoryContext
	(*Message)(nil),             // 3: orchestration.v1.Message
	(*ExecuteNodeResponse)(nil), // 4: orchestration.v1.ExecuteNodeResponse
	(*ToolCall)(nil),            // 5: orchestration.v1.ToolCall
}
var file_orchestration_v1_orchestration_proto_depIdxs = []int32{
	1, // 0: orchestration.v1.ExecuteNodeRequest.tools:type_name -> orchestration.v1.Tool
	2, // 1: orchestration.v1.ExecuteNodeRequest.memory:type_name -> orchestration.v1.MemoryContext
	3, // 2: orchestration.v1.MemoryContext.short_term:type_name -> orchestration.v1.Message
	3, // 3: orchestration.v1.MemoryContext.long_term_hits:type_name -> orchestration.v1.Message
	5, // 4: orchestration.v1.ExecuteNodeResponse.tool_calls:type_name -> orchestration.v1.ToolCall
	0, // 5: orchestration.v1.AgentRuntime.ExecuteNode:input_type -> orchestration.v1.ExecuteNodeRequest
	4, // 6: orchestration.v1.AgentRuntime.ExecuteNode:output_type -> orchestration.v1.ExecuteNodeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_orchestration_v1_orchestration_proto_init() }
func file_orchestration_v1_orchestration_proto_init() {
	if File_orchestration_v1_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestration_v1_orchestration_proto_rawDesc), len(file_orchestration_v1_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestration_v1_orchestration_proto_goTypes,
		DependencyIndexes: file_orchestration_v1_orchestration_proto_depIdxs,
		MessageInfos:      file_orchestration_v1_orchestration_proto_msgTypes,
	}.Build()
	File_orchestration_v1_orchestration_proto = out.File
	file_orchestration_v1_orchestration_proto_goTypes = nil
	file_orchestration_v1_orchestration_proto_depIdxs = nil
}
